language: java

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   jdk: oraclejdk8
    # - os: linux
    #   dist: trusty
    #   jdk: oraclejdk9

    - os: osx
      osx_image: xcode9.2

addons:
  apt:
    packages:
      - build-essential

before_install:
  - brew tap caskroom/versions
  - brew cask install java8

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - ./build.sh
